// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB46Vf3zf8F0z00czc9bB9FnAN22JutJC0',
    appId: '1:236732814442:web:2ca5a5607659e8412ea613',
    messagingSenderId: '236732814442',
    projectId: 'firstapp-b5194',
    authDomain: 'firstapp-b5194.firebaseapp.com',
    storageBucket: 'firstapp-b5194.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFAWPUf26gpvFzUCMiAgB00dpoLhBMmjY',
    appId: '1:236732814442:android:79960e9240ad8fcf2ea613',
    messagingSenderId: '236732814442',
    projectId: 'firstapp-b5194',
    storageBucket: 'firstapp-b5194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK-zU5hgv_1AKCVwKfg9PCepGKiEYicj0',
    appId: '1:236732814442:ios:e8094fe0579c6a5a2ea613',
    messagingSenderId: '236732814442',
    projectId: 'firstapp-b5194',
    storageBucket: 'firstapp-b5194.appspot.com',
    iosClientId: '236732814442-hd8l2sde1ehu3fvgj1vesudbf1ld2u3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK-zU5hgv_1AKCVwKfg9PCepGKiEYicj0',
    appId: '1:236732814442:ios:9069ff58542b36a12ea613',
    messagingSenderId: '236732814442',
    projectId: 'firstapp-b5194',
    storageBucket: 'firstapp-b5194.appspot.com',
    iosClientId: '236732814442-04719i6ol0p88q1f1jjnd91htjrr34oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseBase.RunnerTests',
  );
}
